### ISSUE TITLE
PyTango minimal version

### ISSUE THREAD

**Issue by fabcor-maxiv** [mxcube/video-streamer#15]
Is there a particular reason why `pytango = ^9.4.1` was chosen as version constraint?

It was changed from `^9.3.0` in this [pull request](https://github.com/mxcube/video-streamer/pull/12).

We run mostly `pytango==9.3.6`, so I guess it would make our life easier if this version was not excluded.

@oldfielj-ansto @marcus-oscarsson

**Comment by marcus-oscarsson** [comment]
That would be fine

**Comment by beteva** [comment]
For information, we had a problem with pyTango 9.3.4. The problem is on the server side. When a device server is started with pyTango 9.3.4, it gives the attribute error. When started with 9.3.3, even a 9.3.4 client works fine.
