### ISSUE TITLE
Infinite loop bug in RedisCamera._set_size()

### ISSUE THREAD

**Issue by HilbertCorsair** [mxcube/video-streamer#26]
There is a small issue [here](https://github.com/mxcube/video-streamer/blob/bb10d4053b3b46c07a4174b56710529196823d7a/video_streamer/core/camera.py#L179)
If the condition is not met the streamer goes into an infinite loop without printing anything. We should make it throw an error if there is a problem with the message.

**Comment by walesch-yan** [comment]
I do not suggest to throw an error, as in that case the streamer would directly close when the streamer is not ready, but adding a log message and retrying every few seconds could be done. 

Essentially the infinite loop would mean that there is just no message in Redis channel yet, therefore the streamer should not start in any case. But thanks for pointing it out!
