### ISSUE TITLE
ModuleNotFoundError: No module named 'video_streamer.redisclient' error

### ISSUE THREAD

**Issue by elmjag** [mxcube/video-streamer#9]
When trying to run `video-streamer` from the [latest commit ](https://github.com/mxcube/video-streamer/commit/00c9f05727f3089daad70066777a5f03a95c80b8)on main branch, it fails with following traceback:

```
$ video-streamer 
Traceback (most recent call last):
  File "/opt/mamba/envs/mxcube/bin/video-streamer", line 5, in <module>
    from video_streamer.main import run
  File "/home/elmjag/mxcube/video/video_streamer/main.py", line 7, in <module>
    from video_streamer.redisclient import run_redis_stream
ModuleNotFoundError: No module named 'video_streamer.redisclient'
```

The import of `video_streamer.redisclient` seems to be introduced in this commit: https://github.com/mxcube/video-streamer/commit/91456231cf281b11960da29067168741e608d62f.

**Comment by walesch-yan** [comment]
Unfortunately, the import I made there was added by mistake and can be removed from main

**Comment by elmjag** [comment]
Thanks for a prompt fix!

May I suggest introducing some test to this package, to catch these kind of errors (:
